### ISSUE TITLE
Invalid testcases

### ISSUE THREAD

**Issue by FKuerten** [iteratedecks/iteratedecks#14]
Some testc ases are invalid. For example:
Unfusioned repair
./iteratedecks-cli --verify 1:1 PoKC+i QVgZga

The attacking deck has two Enclave Siegeships, which are unique.

Now the problem here is, that I added checks which test for valid decks -- they obviously fail.
@MrHen Any ideas how to handle this? Should we forbid invalid decks in test cases? Should we not check for valid decks?

**Comment by MrHen** [comment]
I vote that we add a flag which turns off deck validation and then add that flag to the tests. These tests came from leftylink and I would rather keep them to show support for cross pollinating test cases.

**Comment by FKuerten** [comment]
sounds reasonable

**Comment by MrHen** [comment]
@Pr4370r14n: Has this been resolved?

**Comment by FKuerten** [comment]
no. I will have a look at this soon

**Comment by FKuerten** [comment]
since the flag is now there I will need to update the invalid testcases to pass the flag

**Comment by FKuerten** [comment]
okay. This is done in the library branch.
The library branch however is not stable yet, as there are other issues.
