### ISSUE TITLE
Formalize Release Process

### ISSUE THREAD

**Issue by MrHen** [iteratedecks/iteratedecks#16]
We should begin approaching a release milestone. A small list of todos:
- Storage of binaries (GitHub just removed the file upload section)
- Versioning + [Git tags](http://learn.github.com/p/tagging.html)
- Release notes
- Create Kongregate forum thread

I can begin much of this investigation while on vacation and will be posting my thoughts below.

**Comment by MrHen** [comment]
**GitHub uploads**

Here is the blog article talking about [removing the upload feature](https://github.com/blog/1302-goodbye-uploads).

We could theoretically build and check binaries into the repository but it really seems like hosting binaries here is no longer a good option.

Pros:
- Keeps everything on GitHub
- Free
- Ownership is easy to transfer

Cons:
- Binaries hosted in source code repos is icky
- Versioning may get troublesome
- Aside from directly linking into files, end user experience for getting our releases will be more complicated than necessary

**Comment by MrHen** [comment]
**Amazon S3**

Here is [Amazon's S3 Customer Agreement](http://aws.amazon.com/agreement/). This is the service recommended by the GitHub blog post. I skimmed through it and it seems basic enough. I will go through the sign up process for this and see if it will work for us.

Pros
- Free

Cons
- Needs a credit card for the basic account
- Attached to my personal Amazon account which may make it difficult to transfer ownership in the future

**Comment by FKuerten** [comment]
Neither of the two solutions looks acceptable right now.
The closest one would be another git repository with only the binaries, but I don't really like that much.

**Comment by FKuerten** [comment]
Tagging versions for release is probably the easiest part. Awesome would be a build server to automate stuff, but for now I can do this manually. At least for linux releases... the windows cross compilations are a bit more involved.

Also we could try simple free webspace for the binaries, depending on the traffic demands I might be able to provide something.

Bitttorent is also an option, but thats getting a bit overkill for our filesize.

**Comment by FKuerten** [comment]
I would suggest starting a release branch of master everytime we want to make a release. The release branch should have a meaningfull name, for example "release-occupation-pack-2" to indicate that this release supports everything up to (and including) the release of the second occpuation pack.
Release branches should not introduce (or remove) features, but of course bugs may be fixed.

I would suggest then to create tags on this branch for the actual releases. Probably named like "release-occupation-pack-2-v1.
I don't think we need to distinguish between different release types, we just increment the number in each branch.
If we ever need alpha releases then we will simply name them after the commit.

**Comment by MrHen** [comment]
I like this plan. This should give us a nice way to track releases etc. GitHub supports the idea of Milestones so I think we should mimic vX style Milestones: Occupation v1 etc. In the case of mini-expansions, I am comfortable keeping them attached to the greater expansion; so Occupation v1,2,3 etc. I don't think we need to distinguish between Occupation Pack 1 at the release level. I expect the new skills to appear in the first pack so any updates between Pack 1 and Pack 2 are likely to be bug fixes and tweaks.

This still does not give us a good way to "ship". In the interim, I can quickly host binaries on my domain. I would much rather find a solution that does not depend on any one person sticking around...
