### ISSUE TITLE
Score for backfire.

### ISSUE THREAD

**Issue by FKuerten** [iteratedecks/iteratedecks#21]
Siege on attacked
./iteratedecks-cli --verify 1:1 P+K8+m RgAr+mgA 

While both the old turn iterator and the new one agree that this is a clear victory, they disagree in the number of points this should award.
The old one (by NETRAT) says 20.71 points, while the new one (by me) says 25 points.

Can anyone enlighten me?

**Comment by MrHen** [comment]
Relevant Kong discussion: http://www.kongregate.com/forums/65-tyrant/topics/319214-raid-anp-sims-dont-match-and-hhs-completion-raid#posts-6724747

From Moraku: "I’m pretty sure Backfire does count towards points, as I used to abuse that mechanic to get full points back when I did the raid. I don’t know if anything has changed since then though."

**Comment by FKuerten** [comment]
Good to know. Lets see how we can add this extra rule. Makes things more complicated :/

**Comment by FKuerten** [comment]
As it looks the following is happening in the old code:

<pre>
Turn 12 starts
[   9|C "Emanuel" H:8] picks [  16|S "GDR Core" H:10 D:6]
[  21|U "Marauder" A:1 H:2 D:0] begins attack
[  21|U "Marauder" A:1 H:2 D:0] tries to attack [  19|U "Render" A:1 H:9 D:0] ...
[  19|U "Render" A:1 H:8 D:0] suffered 1 damage
On Attack [  19|U "Render" A:1 H:8 D:0] Siege 3 [  41|S "GDR Core" H:10 D:6]
[  41|S "GDR Core" H:7 D:6] suffered 3 damage
[  21|U "Marauder" A:1 H:2 D:0] ends attack
[  25|U "Marauder" A:1 H:2 D:0] begins attack
[  25|U "Marauder" A:1 H:2 D:0] tries to attack [  23|U "Render" A:1 H:9 D:0] ...
[  23|U "Render" A:1 H:8 D:0] suffered 1 damage
On Attack [  23|U "Render" A:1 H:8 D:0] Siege 3 [  41|S "GDR Core" H:7 D:6]
[  41|S "GDR Core" H:4 D:6] suffered 3 damage
[  25|U "Marauder" A:1 H:2 D:0] ends attack
[  29|U "Marauder" A:1 H:2 D:0] begins attack
[  29|U "Marauder" A:1 H:2 D:0] tries to attack [  27|U "Render" A:1 H:9 D:1] ...
[  27|U "Render" A:1 H:8 D:1] suffered 1 damage
On Attack [  27|U "Render" A:1 H:8 D:1] Siege 3 [  41|S "GDR Core" H:4 D:6]
[  41|S "GDR Core" H:1 D:6] suffered 3 damage
[  29|U "Marauder" A:1 H:2 D:0] ends attack
[  33|U "Marauder" A:1 H:2 D:0] begins attack
[  33|U "Marauder" A:1 H:2 D:0] tries to attack [  31|U "Render" A:1 H:9 D:2] ...
[  31|U "Render" A:1 H:8 D:2] suffered 1 damage
On Attack [  31|U "Render" A:1 H:8 D:2] Siege 3 [  41|S "GDR Core" H:1 D:6]
[  41|S "GDR Core" H:0 D:6] died!
[   9|C "Emanuel" H:0] died!
[  33|U "Marauder" A:1 H:2 D:0] ends attack
[  37|U "Marauder" A:1 H:2 D:0] begins attack
[  37|U "Marauder" A:1 H:2 D:0] tries to attack [  35|U "Render" A:1 H:9 D:3] ...
[  35|U "Render" A:1 H:8 D:3] suffered 1 damage
On Attack [  35|U "Render" A:1 H:8 D:3] Siege 3 failed because there is no target
[  37|U "Marauder" A:1 H:2 D:0] ends attack
Turn 12 ends
Turn 13 starts
[   1|C "Freddie" H:12] Heal 1 [  19|U "Render" A:1 H:8 D:0]
[   1|C "Freddie" H:12] Heal 1 [  23|U "Render" A:1 H:8 D:0]
[   1|C "Freddie" H:12] Heal 1 [  27|U "Render" A:1 H:8 D:0]
[   1|C "Freddie" H:12] Heal 1 [  31|U "Render" A:1 H:8 D:1]
[   1|C "Freddie" H:12] Heal 1 [  35|U "Render" A:1 H:8 D:2]
[  19|U "Render" A:1 H:9 D:0] Supply 2 failed because there is no target
[  23|U "Render" A:1 H:9 D:0] Supply 2 failed because there is no target
[  27|U "Render" A:1 H:9 D:0] Supply 2 failed because there is no target
Simulation 0 ends
</pre>

We can see that even though "Emanuel" died in Turn 12 the simulator continues to run turn 13.

With the new code (no debugging support yet) there seems to be no turn 13. 

However this is probably not the for the score difference. This should amount to only one point.

Not sure how to proceed. Could anyone tell me that the ANP should be?

**Comment by MrHen** [comment]
Archiving repo and closing all issues.
