### ISSUE TITLE
--verify should support ANP

### ISSUE THREAD

**Issue by MrHen** [iteratedecks/iteratedecks#22]
Due to issues such as #21, we need a way to test ANP values.

**Comment by FKuerten** [comment]
true. Maybe something like
--verify-points or --verify-anp
should take one or two arguments (one: verify only attacker points. two: verify both points)
basically same syntax as verify, of course the number range will be larger

**Comment by FKuerten** [comment]
After looking at the code again I noticed there are 4 values: Auto/manual attack/def.
We might consider different options; four in sequence might be confusing (Its reasonable to remember that attacker comes before defender, but which comes first auto or manual?)

This also brings me to a related issue:
Sometimes it makes sense to switch to auto after playing half cards on manual (simple example: enemy at 10 health, you know your ogre will crush for 5 this turn and kill the next, so you turn on auto and get more score in the next round) currently the simulator does not support anything like that. Would that be relevant?

**Comment by MrHen** [comment]
Minmaxers are going to care about turning on Auto part way through but I am not sure we should worry about that at the simulation level.

I think reporting the primary deck's Auto and Manual ANP is absolutely necessary. Reporting the secondary deck's ANP is also useful for determining spread -- but I am not sure how we could get the secondary deck on manual? Tournaments ignore points and only count wins and there is no other way to get both primary and secondary decks on manual.

I would prefer to ignore complications such as Ordered not being compatible with Auto ANP. The user will have to user their brain and the minmaxers would still like the information.

As for --verify-anp, I do not have a strong preference. I would like to eventually have a format that is easier to share with the other simulators... but I don't know that any of them are actually using test cases right now. So many it is not worth chasing until later.

**Comment by FKuerten** [comment]
The simulator could (in theory) run both decks ordered. There is no use case however.
Likewise it can calculate manual and auto ANP for both decks.

Opponents auto ANP are probably relevant for faction wars.

Its not like we could not change the format if needed.

**Comment by MrHen** [comment]
--verify is obsolete now that I am using the test repo.

@Pr4370r14n, do you care if I close this down? Do you still want to maintain a set of tests aside from the test repo? (Er, do you know about the test repo?)

http://www.kongregate.com/forums/65-tyrant/topics/328087-for-sims-public-test-case-repository?page=1

**Comment by FKuerten** [comment]
no, I did not.

**Comment by FKuerten** [comment]
Care to sum this up for me?

**Comment by FKuerten** [comment]
In particular, why is this issue obsolete? I see a list of test cases, which is great. But I don't understand how they are run against ID.

Also, the repo does not seem to contain ANP. Is this intentional?

**Comment by MrHen** [comment]
The repo does contain ANP:

http://haileon.com/SimTyrantJS_ListTestCases?pre=1&deckIdList=46f159aedd93f98979c6d9229728d290

The summary is that you can request a json data file from haileon.com which results in a bunch of tests formatted very similar to how the fansite submission API works. The fansite wrapper that I wrote supports a "test mode" that will download and run the tests from the repo.

iteratedecks currently passes a majority of these tests but there are a few it does not; the ANP test linked above is one failure. The others are all related to weird On Death behaviors around already played cards and thinks like Jam.

Whenever I would have written a new testcase I instead add it to the repo; the developers from SimTyrant and T_O do the same. (And I think a few private simulators may also be using the repo.)

So, the tl;dr is that this is a public testcase repo hosted by Moraku. To run them you need to use https://github.com/iteratedecks/fansiteSubmission.

**Comment by MrHen** [comment]
To create a new testcase, start from the kong thread I linked earlier. It has more links and information.

**Comment by MrHen** [comment]
Archiving repo and closing all issues.
