### ISSUE TITLE
Weaken On attacked should not target attacking unit

### ISSUE THREAD

**Issue by MrHen** [iteratedecks/iteratedecks#23]
Weaken On attacked will be changed to target active units _other_ than the attacking unit. I am not sure how we are currently handling this.

Kong thread and relevant Dev post: http://www.kongregate.com/forums/65-tyrant/topics/319662-to-devs-rams-head-wastes-weaken-on-units-that-have-already-attacked#posts-6731781

DaWayne33: "Although the unit that attacks a Ram’s Head could have Flurry or Swipe and the weaken could be relevant. It is much more likely that the skill is wasted on the unit that just attacked. We have changed it so it will only target units that have not yet attacked. This change will go up with the next expansion update."

**Comment by FKuerten** [comment]
I have no idea either right now.
Might be a good idea to check the rules for similar stuff, like "jam on attacked", "freeze on attack" (probably does not exsits), "chaos on attack"

**Comment by hunterhogan** [comment]
In the thread Moraku mentioned that Tazerok had the same issue and change. If you can figure out how ID handled Tazerok, then treat Ram’s Head the same way. In might be that ID is already coded to handle it the “new” way.

**Comment by MrHen** [comment]
I do have a Tazerok test but I don't think [the test] cares about whether the attacker gets hit by the weaken. Honestly, I would not be surprised if our update for On Kill fixed this issue too.

**Comment by hunterhogan** [comment]
Tazerok cares if the attacker has Flurry.
