### ISSUE TITLE
Submitting results to Fansite

### ISSUE THREAD

**Issue by MrHen** [iteratedecks/iteratedecks#24]
sss1 has mentioned that the Fansite will be able to accept submissions for decks. Is this a feature we care about supporting from the CLI? Or would this be more appropriate for a GUI?

http://www.kongregate.com/forums/65-tyrant/topics/289416-simtyrant-the-simulator-that-runs-from-your-browser?page=19#posts-6655798

sss1: "fansite will accept any source of simulation data soon, once i’ll finish all that coding."

**Comment by hunterhogan** [comment]
Please put this in the CLI somehow or ID will become less relevant. ID is much faster than ST or T_O, but if the results from ID cannot be submitted until the GUI is created, then the only results we will have are from the slower simulators. Because they are slower, most people only run 10,000 sims for their results and while maybe that is enough for a mission, it is barely enough for a Raid and certainly not enough for a Quest.

**Comment by MrHen** [comment]
Some of the feasibility here is unknown until we see sss1's plan. What we might be able to do is create a submission tool that simply wraps around the CLI and submits the results. More will be discussed as we learn more.

**Comment by FKuerten** [comment]
If it is like the old submission feature, i.e, visiting a simple url, than supporting this should be quite trivial. sss1 also mentioned something about security features against malicious submissions. We probably should not worry too much until we know more.

**Comment by hunterhogan** [comment]
True. Last time it was just a URL, so I don’t think you need to get fancy and make a new tool, just have the output include a copy&paste URL/code for submission.

**Comment by MrHen** [comment]
I got some information from sss1 and the implementation is not going to be as simple as sending results to a URL. We will probably need to create a wrapper that can ping the Fansite for information, run simulations and then return the results back to the Fansite.

More details, obviously, when sss1 releases something.

**Comment by hunterhogan** [comment]
Ah. Well, I hope he keeps it simple for you to code. You guys already have enough things to worry about.

**Comment by MrHen** [comment]
@Pr4370r14n 

No pressure, just FYI that sss1 has posted the first draft of the submission API. Let me know if you can or cannot see it.

http://tyrant.40in.net/kg/sim.php
http://tyrant.40in.net/kg/sim.php?sim_id=c2bd1IFw

**Comment by FKuerten** [comment]
Yes I can see it.
I also took a quick glance at the API docs. Have not found anything
troubling yet.

I think result submission is not part of the core.
In particular because I do not want dependencies on HTTP in core.
So ideally this should be part of the CLI.

I wish I had finished the library refactoring by now :(
Will not happen before april though :(

**Comment by MrHen** [comment]
The API assumes that people are simply going to "start" the simulator and it goes and grabs stuff to simulate and then returns the results via the API. Chances seem high that we could spin up a third project that gets compiled into its own binary and keeps the CLI dedicated to running whatever the user specifically wants to run.

Or, in other words, I don't think there is much overlap between the CLI and supporting Fansite result submissions.

The other approach is to write a Fansite submission wrapper in something like Python and just translate the sim requests into CLI calls.

**Comment by FKuerten** [comment]
Am Mittwoch, den 27.02.2013, 13:40 -0800 schrieb Adam Babcock:

> The API assumes that people are simply going to "start" the simulator
> and it goes and grabs stuff to simulate and then returns the results
> via the API. 
> I see. Well that would require a bit more work, but should be
> manageable. Still I would not include that into the core.
> 
> Chances seem high that we could spin up a third project that gets
> compiled into its own binary and keeps the CLI dedicated to running
> whatever the user specifically wants to run.
> Sounds reasonable. I would not put much priority on the fansite stuff
> though: That's great to have but we first need a proper simulation core.
> 
> Or, in other words, I don't think there is much overlap between the
> CLI and supporting Fansite result submissions.
> Probably. We could consider adding a "also submit to fansite" option to
> CLI in the future though (should not be default).
> 
> The other approach is to write a Fansite submission wrapper in
> something like Python and just translate the sim requests into CLI
> calls.
> Also fine. In the end that is the idea of a small core.

P

**Comment by MrHen** [comment]
I went with the Python wrapper:

https://github.com/iteratedecks/fansiteSubmission/

This was explicitly more programmer friendly than user friendly but I am not sure we really need the average user submitting to the Fansite. Between me and hunterhogan we already have a 100% coverage rating.

Future improvements to the submission process should be filed as issues on that project.
