### ISSUE TITLE
Strike On Kill can hit something in the middle of Swipe

### ISSUE THREAD

**Issue by MrHen** [iteratedecks/iteratedecks#25]
This seems like a likely failure point. This issue is to remind me to write a test scenario covering this.

http://tyrant.40in.net/card.php?id=724#comments:pid=11535

jimbo_extreme: "Lets say It kills the unit to the left and then strikes the unit in the middle (infront of it), killing that unit. Will it continue its swipe or abruptly stop? And If it stops will it still attack commander directly?"

**Comment by FKuerten** [comment]
Do we already know the answer?
Current implementation will probably continue to strike and hit commander in middle.

Also: Chaosed neverender's on death can trigger the same situation, right?

Lets make a test case. What about this:
<a href="http://tyrant.40in.net/kg/deck.php?nid=PrCFLU"><img src="http://tyrant.40in.net/ig/deck/f81/187745e-PrCFLU.jpg"></a>
vs.
<a href="http://tyrant.40in.net/kg/deck.php?nid=QFCTL0CDvu"><img src="http://tyrant.40in.net/ig/deck/fee/14461c2-QFCTL0CDvu.jpg"></a>
both ordered of course, normal mode.

Round 1 and 2 they each summon, nothing happens.
Round 3 Slag Driller is summoned.
Round 4 Joltrek is summoned.
Round 5 Slag Driller is still delayed.
Round 6 Blood Grunt is summoned. Joltrek will hit Slag driller for 3 but not kill it.
Round 8 Slag Diller attacks, will certainly kill Median. Will then strike. This should hit Joltrek (intercept) and kill Joltrek.
Case 1: Swipe continues.Blood Grunt will die. 
Attacker will eventually win.
Case 2: Blood grunt survives round 8.
Round 9: Power Surge rallies Beholder for 3, Malort rallies Beholder  for 1. Beholder one hits Whisper.

We need someone with the cards to test that. Could be a problem to get the right order for defender though :(
Maybe you can come up with a simpler test case.

**Comment by MrHen** [comment]
I would expect Beholder to die; I think the question was whether Slag Driller's attack in the middle goes through to the commander since, if there were no assault there originally, it would not have triggered Swipe.

But yeah, a chaosed strike on death could produce the same issue.

**Comment by FKuerten** [comment]
Okay. I confirmed it: The swipe WILL hit the commander if the middle unit is killed in reaction to the first unit being killed (probably same for attacked). I did not test whether the swipe will hit the third unit.
http://tyrant.40in.net/kg/deck.php?nid=QeHXHLfW
vs
http://tyrant.40in.net/kg/deck.php?nid=PqJ6Jl
(50% chance opponent deck will have wrong order)

There is a 50% chance that Sidoze's weaken will be invaded, in this case the attacker loses.
Otherwise I could observe QB swiping Marshal to death, its chaosed strike 2 on death (which can not be invaded) killing Dark Wings and then QB swiping Cyrus to death.

**Comment by MrHen** [comment]
This was recently confirmed again on Kong:

http://www.kongregate.com/forums/65-tyrant/topics/289416-simtyrant-the-simulator-that-runs-from-your-browser?page=22#posts-6861821

elbonians: "So I’ll share what I know about the Slag Driller:

http://haileon.com/SimTyrantJS?deck1=QVFqLU&amp;deck2=PoAB+i&amp;exactorder=1&amp;sims=100&amp;debug=1

On turn 7, his swipe attacks to the left, killing infantry(0), then the on-kill strike kills infantry(1), and then, at that point, with swipe begun but suddenly no card facing him, Tyrant actually will allow him to hit the commander in this case."
