### ISSUE TITLE
Jam should not prevent Payback

### ISSUE THREAD

**Issue by MrHen** [iteratedecks/iteratedecks#26]
I found a good list of the skills here on Kong:

http://www.kongregate.com/forums/65-tyrant/topics/316848-guide-skills?page=1#posts-6680342

Some of the statements jumped out at me as good edge cases:

"Payback(Defensive)
 If an enemy activation skill is used on this unit, 50% use the same skill on the original unit(keeps augmented value, removes all and faction restictions) (Jam does not work on this, as it is not an activation skill)."

We should have a test that determines if Payback triggers even if the unit has been Jammed.

**Comment by FKuerten** [comment]
lets see... obviously this will not be a 100% test, as jam has 50% miss chance... hmm.
What about this?
<a href="http://tyrant.40in.net/kg/deck.php?nid=SBgy+jAl">SBgy+jAl</a> ordered vs <a href="http://tyrant.40in.net/kg/deck.php?nid=PoLd">PoLd</a>

Hunter will activate first, killing the opponent. (Strike 1 plus attack 3).
Opponent will be jammed with about 1-(0.5)^4 = 93%.
If jam does not affect payback, Payback will in 50% kill hunter. So we expect 50% win and 50% time out.
If jam does prevent payback then winrate should be much higher, close to 96%.

**Comment by MrHen** [comment]
I would prefer to go with a scenario that uses fewer units, even if the difference between correct and wrong is closer:

[SBAl](http://tyrant.40in.net/kg/deck.php?nid=SBAl) vs [PoNh](http://tyrant.40in.net/kg/deck.php?nid=PoNh)

But the basic principle is the same.
