### ISSUE TITLE
Support card ids greater than 4000

### ISSUE THREAD

**Issue by MrHen** [iteratedecks/iteratedecks#28]
http://www.kongregate.com/forums/65-tyrant/topics/319835-to-third-party-devs-expanding-hash-notation

The next update will push the cards past 4000 which means we need to handle the new hash notation.

**Comment by FKuerten** [comment]
That sounded like there is an agreed standard. Your link does not really look like its decided. I commented there.
In the end is think that is an UI problem, internally we should not have a problem with that.
(However currently type is decided on id, so maybe there is some work needed.)

**Comment by MrHen** [comment]
Moraku has already implemented it:

http://www.kongregate.com/forums/65-tyrant/topics/289416-simtyrant-the-simulator-that-runs-from-your-browser?page=21#posts-6826697

We could always let people send in id lists too. Doesn't matter to me just so long as everything is compatable with each other.

**Comment by MrHen** [comment]
sss1 has also implemented it:

http://www.kongregate.com/forums/65-tyrant/topics/319835-to-third-party-devs-expanding-hash-notation#posts-6767307

So if the Fansite and SimTyrant and ourselves are doing I think that is enough to make it the new standard. Although I still like the idea of support id lists, too.

**Comment by FKuerten** [comment]
(Im currently writing my master's thesis, which is due end of march. I will probably not do much here until seen.)
If we support the standard thats fine.

**Comment by FKuerten** [comment]
Okay, unbury this... as this is not working.
Blocked by issue #59

**Comment by MrHen** [comment]
Well, they are working in the sense that the current binaries accept hashes just fine... :P

**Comment by FKuerten** [comment]
Not on all branches though.

**Comment by MrHen** [comment]
Ah, okay, that makes sense.

**Comment by FKuerten** [comment]
fixed on library branch. I don't like the hash system and I will probably deprecate it in version 3
