### ISSUE TITLE
On Attack summons do not downtick on the next turn

### ISSUE THREAD

**Issue by MrHen** [iteratedecks/iteratedecks#3]
[Copied from email]

QMMB (Dementia, Egg Infector)
vs
QVAB (Dracorex, Infantry)

Deck2 will never win as the infantry can never kill the Egg Infector (against Dementia's heal).

Deck1 is a bit more complicated. At a quick glance Egg Infector will never deal damage because of Dracorex weaken all. But the summoned mites will, according to your quote, do one damage on the first round.

So eventually deck 1 should win after about 18 turns.

No lets see what our simulator says:

> $ ./iteratedecks-cli QMMB QVAr
> Games won:             0 /       1000 
> Games lost:            0 /       1000 
> Games drawn:        1000 /       1000 
> estimator=0.0000 confidence [0.0000;0.0027]; ANP=0.0000

Okay. All tied (which is a better word than drawn, but thats off topic
now.)

Hmm... that was not what we expected. So lets look in detail:
One iteration should be enough as there is no randomness at all.

First three turns:
$ ./iteratedecks-cli --verbose QMMB QVAr -n 1

> Simulation 0 starts
> Turn 1 starts
> [   1|C "Dementia" H:13] picks [   2|U "Egg Infector" A:1 H:7 D:3]
> [   1|C "Dementia" H:13] Heal Bloodthirsty 1 failed because there is
> no target
> Turn 1 ends
> Fine so far.
> Turn 2 starts
> [   4|C "Dracorex" H:9] picks [   5|U "Marauder" A:1 H:2 D:0]
> [   4|C "Dracorex" H:9] Weaken 1 failed because there is no target
> Okay, looks solid: Dracorex "Weaken 1 all" could not find a target as Egg Infector is still on delay. There is no Mite yet.
> [  10|U "Marauder" A:1 H:2 D:0] begins attack
> [  10|U "Marauder" A:1 H:2 D:0] tries to attack [   8|U "Egg Infector"
> A:1 H:7 D:2] ...
> [   8|U "Egg Infector" A:1 H:6 D:2] suffered 1 damage
> On Attack [   8|U "Egg Infector" A:1 H:6 D:2] summons [  12|U "Mite"
> A:1 H:4 D:1]
> [  10|U "Marauder" A:1 H:2 D:0] ends attack Turn 2 ends
> Okay, we have a mite summoned, it has delay 1.
> Turn 3 starts
> [   1|C "Dementia" H:13] Heal 1 [   8|U "Egg Infector" A:1 H:6 D:2]
> Commander heals, fine.
> Turn 3 ends
> Wait. Why did our mite not attack?

After this point this just repeats: Mites get summoned, not weakened on first turn, but do not attack.

**Comment by FKuerten** [comment]
Should be resolved in branch fix-timer.
