### ISSUE TITLE
Frozen should not disable On Death or On Attacked abilities

### ISSUE THREAD

**Issue by MrHen** [iteratedecks/iteratedecks#31]
Kong post:

http://www.kongregate.com/forums/65-tyrant/topics/289416-simtyrant-the-simulator-that-runs-from-your-browser?page=21#posts-6848875

**Comment by FKuerten** [comment]
That is interesting. I always assumed freeze was a more powerfull version of jam.

**Comment by MrHen** [comment]
A test for this is in the repo and we are passing it. I don't remember explicitly fixing this... so maybe we were already handling it properly?

http://haileon.com/SimTyrantJS_ListTestCases?pre=1&deckIdList=0478eea7105584b57acf61fbf2691512

**Comment by FKuerten** [comment]
I kind of doubt it. Just to clarify: Jam does prevent this, and frozen prevents the unit to be a target for jam?
