### ISSUE TITLE
Implement Legion skill

### ISSUE THREAD

**Issue by MrHen** [iteratedecks/iteratedecks#33]
Preliminary information about the new Legion skill is being collected on Kong:

http://www.kongregate.com/forums/65-tyrant/topics/326684-guide-worldship-skills

**Comment by MrHen** [comment]
I have a basic implementation for this but don't know what the proper behavior is for the nitty gritty details. Chances are high I have something wrong but I don't have any Legion cards to test it with.

**Comment by FKuerten** [comment]
Sorry, I don't have any either. But I am pretty sure we can find someone
who has.
