### ISSUE TITLE
Compile Issues?

### ISSUE THREAD

**Issue by mcavolowsky** [iteratedecks/iteratedecks#35]
So I could just be an idiot, but I'm trying to build your trunk from source.  I'm not a developer, but I've done more than my fair share of coding and I know my way around Ubuntu well enough.  I found my way round a few bugs that were my problem (didn't have git-svn package, just git-core), but I can't seem to get it to build for the life of me.

I run `makepp CLI` in the linux-on-linux directory and it gives the following errors

```
makepp: Loading makefile `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/Makeppfile'
makepp: Loading makefile `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/Makeppfile'
Unable to determine upstream SVN information from working tree history

makepp: Loading makefile `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/TEST/Makeppfile'
makepp: Loading makefile `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/bin/Makeppfile'
makepp: warning: command parser not found for rule at `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/cli.Makeppfile:12(linux-on-linux)'
although it seems to be a compilation command.  This means that makepp will
not detect any include files.  To specify a parser for the whole rule,
add a :parser modifier line to the rule actions, like this:
    : parser gcc-compilation    # Scans source for include files.
or
    : parser none       # Does not scan, but suppresses warning.
Or to do it on a per command basis, if you have such obscure commands:
register-parser my_obscure_cc_wrapper   skip-word
register-parser my_obscure_cc       c-compilation
makepp: Entering directory `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux'
not-found  -g  --std=c++11  -c CLI2/iteratedecks-cli.cpp -o CLI2/iteratedecks-cli.o
exec not-found  -g  --std=c++11  -c CLI2/iteratedecks-cli.cpp -o CLI2/iteratedecks-cli.o failed--No such file or directory
makepp: Failed to build target `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CLI2/iteratedecks-cli.o' [254]
makepp: 0 files updated, 0 phony targets built and 1 target failed
/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/cli.Makeppfile:8(linux-on-linux): infer_objects failed because dependencies could not be built
```

If you guys have any ideas on what's going on, I'd appreciate it.  I'd love to try out your code (and maybe even help you guys out with a thing or two here or there).

Thanks!

**Comment by FKuerten** [comment]
Am Mittwoch, den 27.02.2013, 15:18 -0800 schrieb obitwokenobi:

> So I could just be an idiot, but I'm trying to build your trunk from
> source. I'm not a developer, but I've done more than my fair share of
> coding and I know my way around Ubuntu well enough. I found my way
> round a few bugs that were my problem (didn't have git-svn package,
> just git-core), but I can't seem to get it to build for the life of
> me.

You should not need git-svn at all. That is probably some old code in
the Makeppfile I forgot to remove.

> I run makepp CLI in the linux-on-linux directory
> That is the right command to run. Should not give errors though.
> Your errors are incomprehensible for me at the moment.
> 
> If you guys have any ideas on what's going on, I'd appreciate it. I'd
> love to try out your code (and maybe even help you guys out with a
> thing or two here or there).

Maybe it is just an version incompatibility... but probably its the
Makeppfile

I pushed a quick fix attempt, let me know if it works.
If it does not, please give us the following:
$ makepp --version
$ perl --version
$ g++ --version

P

**Comment by mcavolowsky** [comment]
Ok, so the above problem seems to be that I was missing g++.  That seems to get me closer, but it still errors out before the end.  The versions of the above software are:

```
mark@MediaServer:~/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux$makepp --version
makepp version 2.0
Makepp may be copied only under the terms of either the Artistic License or
the GNU General Public License, either version 2, or (at your option) any
later version.
For more details, see the makepp homepage at http://makepp.sourceforge.net.
```

```
mark@MediaServer:~/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux$ perl --version

This is perl 5, version 14, subversion 2 (v5.14.2) built for x86_64-linux-gnu-thread-multi
(with 64 registered patches, see perl -V for more detail)

Copyright 1987-2011, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

```
mark@MediaServer:~/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux$ g++ --version
g++ (Ubuntu/Linaro 4.7.2-2ubuntu1) 4.7.2
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

After installing g++ I deleted the old files completely and re-cloned the git at `git clone git://github.com/iteratedecks/iteratedecks.git`.  Running `makepp CLI` in `builddir/linux-on-linux` gives the following.

```
sudo makepp CLI
makepp: Loading makefile `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/Makeppfile'
makepp: Loading makefile `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/Makeppfile'
makepp: Loading makefile `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/TEST/Makeppfile'
makepp: Loading makefile `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/bin/Makeppfile'
makepp: warning: can't locate file ../../EvaluateDecks/getopt_mb_uni_vc10/getopt_mb_uni_vc10_dll/getopt.h, included from `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CLI2'
Include path [user] is:
  [including file's directory]
  /usr/local/include
  /usr/include
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/cardDB.cpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/cardDB.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/compat.h'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/deckIndex.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/assert.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/cardSet.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/cardPool.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/activeDeck.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/pugixml/src/pugixml.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/pugixml/src/pugixml.cpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/card.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/missionInfo.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/raidInfo.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/bgInfo.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/achievementInfo.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/stepInfo.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/skill.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/simpleTypes.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/activeDeck.forward.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/deckIndex.forward.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/exceptions.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/assert.tpl.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/assert.inline.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/cardPool.forward.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/card.forward.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/playedCard.forward.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/playedCard.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/results.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/logger.forward.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/pugixml/src/pugiconfig.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/constants.hpp'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/log.h'
makepp: Scanning `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/deck.hpp'
makepp: Entering directory `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux'
g++  -g -Wall  --std=c++11  -c CORE/cardDB.cpp -o CORE/cardDB.o
In file included from CORE/cardDB.cpp:6:0:
CORE/compat.h:6:2: warning: #warning "Compability mode!" [-Wcpp]
CORE/cardDB.cpp:24:48: fatal error: boost/algorithm/string/predicate.hpp: No such file or directory
compilation terminated.
makepp: Failed to build target `/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/linux-on-linux/CORE/cardDB.o' [1]
makepp: 0 files updated, 0 phony targets built and 1 target failed
/home/mark/Downloads/Tyrant/Simulator/iteratedecks/builddir/cli.Makeppfile:8(linux-on-linux): infer_objects failed because dependencies could not be built
```

Are there any other packages that I might need for this?  I don't do software development, so even the obvious ones may not be so obvious to me...

-Mark

**Comment by FKuerten** [comment]
Versions are fine now, g++ was obviously essential.

CORE/cardDB.cpp:24:48: fatal error: boost/algorithm/string/predicate.hpp: No such file or directory
compilation terminated.

That line kinda tells you that libboost is required.
On my debian I have
libboost-filesystem-dev
Probably called very similar on Ubuntu.
If that does not fix it, I also have libboost-iostreams, libboost-math, libboost-test installed.

**Comment by mcavolowsky** [comment]
Ok, cool.  Adding libboost helped a lot. I think we are _almost_ there, but for some reason it makepp can't find a file during the build, even though it is there.

Now when I compile, it gives this:

```
makepp: Loading makefile `/home/mark/downloads/tyrant/simulator/iteratedecks/builddir/linux-on-linux/Makeppfile'
makepp: Loading makefile `/home/mark/downloads/tyrant/simulator/iteratedecks/builddir/Makeppfile'
makepp: Loading makefile `/home/mark/downloads/tyrant/simulator/iteratedecks/builddir/linux-on-linux/TEST/Makeppfile'
makepp: Loading makefile `/home/mark/downloads/tyrant/simulator/iteratedecks/bin/Makeppfile'
makepp: warning: can't locate file ../../EvaluateDecks/getopt_mb_uni_vc10/getopt_mb_uni_vc10_dll/getopt.h, included from `/home/mark/downloads/tyrant/simulator/iteratedecks/builddir/linux-on-linux/CLI2'
Include path [user] is:
  [including file's directory]
  /usr/local/include
  /usr/include
makepp: Entering directory `/home/mark/downloads/tyrant/simulator/iteratedecks/bin'
./updatexml.sh
wget --quiet http://kg.tyrantonline.com/assets/cards.xml -O cards.xml
wget --quiet http://kg.tyrantonline.com/assets/raids.xml -O raids.xml
wget --quiet http://kg.tyrantonline.com/assets/missions.xml -O missions.xml
wget --quiet http://kg.tyrantonline.com/assets/quests.xml -O quests.xml
wget --quiet http://kg.tyrantonline.com/assets/achievements.xml -O achievements.xml
makepp: Leaving directory `/home/mark/downloads/tyrant/simulator/iteratedecks/bin'
makepp: Entering directory `/home/mark/downloads/tyrant/simulator/iteratedecks/builddir/linux-on-linux'
cp -f ../../bin/achievements.xml achievements.xml
cp -f ../../bin/cards.xml cards.xml
cp -f ../../bin/missions.xml missions.xml
cp -f ../../bin/quests.xml quests.xml
makepp: 9 files updated and 4 phony targets built
```

I thought it could be a permissions issue, but `chmod 777` on all of the files doesn't help at all.

It said it was included by CLI2, so I thought _maybe_ it would still work, but now when I try to test it with `./iteratedecks-cli QVH0+ofc+i P+DA+kBW+iBnBID2Bo`, it errors out with:

```
Assertion failed:
Id in file CORE/cardDB.cpp:246(bool IterateDecks::Core::CardDB::LoadCardXML(const char*, char*, size_t))
Stacktrace available, most recent call on top: 5 items
#  shared object                            -- function
 0 failed to resolve name and file for 0x4433cf this is probably due to a static build.
 1 failed to resolve name and file for 0x4054a8 this is probably due to a static build.
 2 failed to resolve name and file for 0x40599d this is probably due to a static build.
 3 failed to resolve name and file for 0x4dfc94 this is probably due to a static build.
 4 failed to resolve name and file for 0x401441 this is probably due to a static build.
```

I'm going to try some things to get it to build over the weekend, but do you have any thoughts?

Also, I was thinking of filling out the wiki with a build page to document some of these problems and fixes.  Let me know if you don't want that, so feel free to delete it if you wish.

-Mark

**Comment by FKuerten** [comment]
Am Freitag, den 01.03.2013, 14:45 -0800 schrieb obitwokenobi:

> Ok, cool. Adding libboost helped a lot. I think we are almost there,
> but for some reason it makepp can't find a file during the build, even
> though it is there.
> 
> Now when I compile, it gives this:
> 
> makepp: Loading makefile `/home/mark/downloads/tyrant/simulator/iteratedecks/builddir/linux-on-linux/Makeppfile'
> makepp: Loading makefile`/home/mark/downloads/tyrant/simulator/iteratedecks/builddir/Makeppfile'
> makepp: Loading makefile `/home/mark/downloads/tyrant/simulator/iteratedecks/builddir/linux-on-linux/TEST/Makeppfile'
> makepp: Loading makefile`/home/mark/downloads/tyrant/simulator/iteratedecks/bin/Makeppfile'
> makepp: warning: can't locate file ../../EvaluateDecks/getopt_mb_uni_vc10/getopt_mb_uni_vc10_dll/getopt.h, included from `/home/mark/downloads/tyrant/simulator/iteratedecks/builddir/linux-on-linux/CLI2'
> Don't worry about that one. This is a strange warning, I get it too.
> Include path [user] is:
>   [including file's directory]
>   /usr/local/include
>   /usr/include
> makepp: Entering directory`/home/mark/downloads/tyrant/simulator/iteratedecks/bin'
> ./updatexml.sh
> wget --quiet http://kg.tyrantonline.com/assets/cards.xml -O cards.xml
> wget --quiet http://kg.tyrantonline.com/assets/raids.xml -O raids.xml
> wget --quiet http://kg.tyrantonline.com/assets/missions.xml -O missions.xml
> wget --quiet http://kg.tyrantonline.com/assets/quests.xml -O quests.xml
> wget --quiet http://kg.tyrantonline.com/assets/achievements.xml -O achievements.xml
> makepp: Leaving directory `/home/mark/downloads/tyrant/simulator/iteratedecks/bin'
> makepp: Entering directory`/home/mark/downloads/tyrant/simulator/iteratedecks/builddir/linux-on-linux'
> cp -f ../../bin/achievements.xml achievements.xml
> cp -f ../../bin/cards.xml cards.xml
> cp -f ../../bin/missions.xml missions.xml
> cp -f ../../bin/quests.xml quests.xml
> makepp: 9 files updated and 4 phony targets built
> Thats generally a successfull build.
> 
> I thought it could be a permissions issue, but chmod 777 on all of the
> files doesn't help at all.
> No need to make source files executable.
> 
> It said it was included by CLI2, so I thought maybe it would still
> work, but now when I try to test it with ./iteratedecks-cli QVH0+ofc+i
> P+DA+kBW+iBnBID2Bo, it errors out with:
> 
> Assertion failed:
> Id in file CORE/cardDB.cpp:246(bool IterateDecks::Core::CardDB::LoadCardXML(const char_, char_, size_t))
> I don't know what that means right now, but that most probably is a bug
> in the actual implementation and not in the build chain.
> I get the same error with that example.

Some guesses: Incorrect hash format, correct format but the card does
not exist, something fishy with the exact card.

> Stacktrace available, most recent call on top: 5 items
> 
> # shared object                            -- function
> 
>  0 failed to resolve name and file for 0x4433cf this is probably due to a static build.
>  1 failed to resolve name and file for 0x4054a8 this is probably due to a static build.
>  2 failed to resolve name and file for 0x40599d this is probably due to a static build.
>  3 failed to resolve name and file for 0x4dfc94 this is probably due to a static build.
>  4 failed to resolve name and file for 0x401441 this is probably due to a static build.
> Thats because you used the release build. Try building in
> linux-on-linux-debug to get a proper stacktrace.
> You should use the debug build in general is something is strange.
> 
> I'm going to try some things to get it to build over the weekend, but
> do you have any thoughts?
> It does build. This is most likely a bug in the codebase. I get the same
> error.
> 
> Also, I was thinking of filling out the wiki with a build page to
> document some of these problems and fixes. Let me know if you don't
> want that, so feel free to delete it if you wish.
> Sure go ahead.

P

**Comment by MrHen** [comment]
If you are building in the master branch it is probably choking on Worldship card ids and/or skills. Build from the worldship branch until I get things merged (hopefully later today).

**Comment by mcavolowsky** [comment]
Sweet, well it took me a bit to get the branch working, but Worldship seems to do the trick for me.  It isn't stable 100% of the time, but it's an improvement over before and it is probably just be user error.

Thanks, guys!
