### ISSUE TITLE
On Kill and Counter order of operations

### ISSUE THREAD

**Issue by MrHen** [iteratedecks/iteratedecks#37]
From Moraku:

"When an Assault with an “On Kill” ability kills an Assault with Counter, it will force the all units on the field attempt to Regenerate if they can before Counter damage takes place (Normally Counter damage comes before Regenerate!)."

http://www.kongregate.com/forums/65-tyrant/topics/312572-guide-occupation-skills?page=5#posts-6885934

**Comment by FKuerten** [comment]
I get the impression that there are almost as many dirty hacks in the
game as we have in the simulator.

**Comment by MrHen** [comment]
Archiving repo and closing all issues.
