### ISSUE TITLE
Exact order

### ISSUE THREAD

**Issue by MrHen** [iteratedecks/iteratedecks#38]
Some people have found it useful to have an exact order flag that essentially ignores hand size and forces the cards to be played in a specific order. This also seems useful for testcases.

**Comment by FKuerten** [comment]
Usefull for what, besides testcases?

**Comment by MrHen** [comment]
I don't really know. But they convinced Moraku to add it to SimTyrant.

**Comment by MrHen** [comment]
Some relevant Kong discussion:

http://www.kongregate.com/forums/65-tyrant/topics/328087-sims-public-test-case-repository#posts-6890490

**Comment by FKuerten** [comment]
current status is:
will not implement
(but as this is an open source project you are invited to do so yourself, and I will give assistance if needed)
