### ISSUE TITLE
Backfire bugs

### ISSUE THREAD

**Issue by MrHen** [iteratedecks/iteratedecks#4]
leftlink posted a set of scenarios we are not handling appropriately.

http://www.kongregate.com/forums/65/topics/195043?page=73#posts-6619184

> Expected results for the following are all victories, but iteratedecks gives all draws:
>  ./iteratedecks P5 P0gA
>  ./iteratedecks PoI9 PoL3gA
>  ./iteratedecks Pog0 PogA
>  ./iteratedecks Pou7+j P0gA
>  ./iteratedecks P+K8+m RgAr+mgA 
> ./iteratedecks PoKh+i RggA
>  ./iteratedecks PoKF+j RggA -s
> 
> Expected result for the below test is victory, but iteratedecks gives loss:
>  ./iteratedecks RiL3 P0gAJj

**Comment by FKuerten** [comment]
I have not really looked into backfire at all. It seems to be a special case.
It actually is an "on death" effect without being called that.

**Comment by MrHen** [comment]
I have all of these fixed in raid-tests at this point.
