### ISSUE TITLE
Stun Skill

### ISSUE THREAD

**Issue by MrHen** [iteratedecks/iteratedecks#45]
The Stun Skill has been announced:

http://www.kongregate.com/forums/65-tyrant/topics/329275-dev-3-13-2013-worldship-pack-2-announcement

"Stun – Defensive – Any Assault unit that attacks this becomes stunned. Stunned units cannot attack until after their next turn. (can be cleansed)"

Looks like the annoying complications here are when Stunned gets applied and removed.

**Comment by FKuerten** [comment]
Sounds like "immobilize on attack", just that it stays longer.

**Comment by hunterhogan** [comment]
And 100% proc

**Comment by FKuerten** [comment]
Some evil thoughts, maybe they were already addressed elsewhere:
Assume a card has "cleanse on kill" and "swipe" or "flurry" and attacks and kills a card with "stun".
