### ISSUE TITLE
Seed parameter not working as expected

### ISSUE THREAD

**Issue by wiegraff13** [iteratedecks/iteratedecks#63]
Unsure if this is a bug or if I am reading the documentation incorrectly here, though it seems that the seed parameter is not working as expected.

When I run without seed, I always get the same results, whereas the documentation suggests that it would be time-based by default:

> iteratedecks-cli.exe [deck1] [deck2] -n 10000

When I specify seed, but without any seed value, I get different results (based on time) as I would expect:

> iteratedecks-cli.exe [deck1] [deck2] -n 10000 --seed

When I attempt to give the seed a value, the simulator crashes (probably a bug either way):

> iteratedecks-cli.exe [deck1] [deck2] -n 10000 --seed 1

I am running iteratedecks on Windows 7 Professional (64-bit).

**Comment by FKuerten** [comment]
I don't remember what the intention for the first is.
Thats some strange bug with getopt... try "--seed=1"

**Comment by wiegraff13** [comment]
The equals does the trick on the third method.

**Comment by MrHen** [comment]
Archiving repo and closing all issues.
