### ISSUE TITLE
Batch Mode

### ISSUE THREAD

**Issue by wiegraff13** [iteratedecks/iteratedecks#64]
It would be nice if a batch mode were introduced that would allow to run a list of decks against another list of decks as it is useful to test sets of decks against each other when trying to figure out how to improve a deck.

Not sure what form the interface for this should be. Perhaps pass a file path in for the deck parameters that lead to a file with a deck hash on each line.

**Comment by FKuerten** [comment]
Please note that the CLI2 series is reaching end-of-life, that means no new features will be added.
(Everything MrHen releases is CLI2 series.)

Of course I could add this to CLI3. However I do not see the point right now. Maybe you can give me a better example of what you want and why it cannot be done easily with shell scripting.

**Comment by wiegraff13** [comment]
Actually, I currently am using a script that I built around IterateDecks to do this.

Basically, what I am doing is some brute force analysis of my deck by running many one-off variations of my deck against another static set of decks. My script will then run IterateDecks against every combination.

The reason that I would like the batch functionality within IterateDecks is mainly for performance — the script will run IterateDecks tens of thousands of times in a row so any overhead that can be trimmed (such a launching the application) can speed the whole thing up.

**Comment by FKuerten** [comment]
I see. Makes sense for me, but I doubt this will be a big performance hit. Out of curiosity, what script language are you using?

**Comment by wiegraff13** [comment]
It was something quick that I threw together in Powershell.

**Comment by FKuerten** [comment]
I will keep this in mind, I don't think this is something likely to happen soon (from my side).
For once I am not sure how the interface should be, i.e, what the input and output should be.

**Comment by wiegraff13** [comment]
Cool, if it gets in there.

The interface is a bit tricky since command-line isn't really favorable for this sort of functionality. I have some thoughts which may help:

Input ideas:
1). Pass in a file path to a file containing the lists. File could be something list a each hash on its own line or a CSV.
2). Pass in a comma separated list as an argument. For bigger batches, one may actually hit the command line length limit though.
3). Have the interface only be programmatically accessible as command-line is weird for this. To be useful this would probably require the simulation core to be a dll. Would be easier to make a GUI around it, though this is a lot more involved.

On output, I have my script is currently piping a tabbed delimited list of the deck hash, a label to easily identify what the variation is, and the win rate. I can then just copy-paste the result into Excel and sort to find which variations are best. Not sure if that is helpful on what a general case output should be though.

**Comment by FKuerten** [comment]
The core is actually, since version 3, a library. It can be used both statically and dynamically. It has a rather high level interface though.
Also no one bothers to compile it for the rarer platforms like yours.

**Comment by MrHen** [comment]
Archiving repo and closing all issues.
