### ISSUE TITLE
Battlegrounds

### ISSUE THREAD

**Issue by FKuerten** [iteratedecks/iteratedecks#7]
At least "Clone experimennt" / "Split 5" seems to be incorrect.

**Comment by FKuerten** [comment]
Apparently there is no code at all for this.

**Comment by FKuerten** [comment]
wrote some code. need to understand how to attach the battleground branch to this bug report.

**Comment by MrHen** [comment]
Does Split 5 split each mod 5/6 or just on turns 5/6?

**Comment by FKuerten** [comment]
Very good question. I read it like "on each fith turn". But it could also be read the opposite way. I suppose we would need to check that. My faction will probably attack one of those tiles later so I might be able to check.

**Comment by FKuerten** [comment]
Okay, seems to be only on the turns 9 and 10.

**Comment by MrHen** [comment]
Archiving repo and closing all issues.
