### ISSUE TITLE
Weaken not used correctly for delay 1

### ISSUE THREAD

**Issue by FKuerten** [iteratedecks/iteratedecks#8]
Consider Draco Ogre Spam in surge against a mission deck with genesis:
http://haileon.com/SimTyrantJS?deck1=QVH0+q&surge=1&ordered=1&mission=240&battleground=10&sims=1000
and
./iteratedecks-cli --surge -b 10 -o QVH0+q --mission-id 240

SimTyrantJS gives 70%, we give 50%.
Now this is probably a nightmare to debug.

**Comment by FKuerten** [comment]
Fortunately, this seems not to be related to Genesis:
http://haileon.com/SimTyrantJS?deck1=QVH0+q&surge=1&ordered=1&mission=240&sims=10000
gives 92%
and 
./iteratedecks-cli --surge -o QVH0+q --mission-id 240 -n 10000
gives 85%

**Comment by FKuerten** [comment]
It is probably also not related to surge. The difference is still there but getting small.

**Comment by FKuerten** [comment]
Got another, smaller diverging example:
http://haileon.com/SimTyrantJS?deck1=QVH0+j&deck2=SKJNJPJqJYI2&surge=1&sims=10000 gives 74%
./iteratedecks-cli --surge QVH0+j SKJNJPJqJYI2 -n 10000 gives 62%

**Comment by FKuerten** [comment]
Still diverging, other direction now. :(
http://haileon.com/SimTyrantJS?deck1=QVH0&deck2=SKJYI2&surge=1&sims=10000 gives 61%
./iteratedecks-cli --surge QVH0 SKJYI2 -n 10000 gives 75%

**Comment by FKuerten** [comment]
Now with a normal commander:
http://haileon.com/SimTyrantJS?deck1=QVH0&deck2=SAJYI2&surge=1&sims=10000 gives 80%
 ./iteratedecks-cli --surge QVH0 SAJYI2 -n 10000 gives 67%

**Comment by FKuerten** [comment]
And no more different cards.
http://haileon.com/SimTyrantJS?deck1=QVH0&deck2=SAI2+i&surge=1&sims=10000 gives 80%
./iteratedecks-cli --surge QVH0 SAI2+i -n 10000 gives 63%

**Comment by FKuerten** [comment]
There is a bug in our simulator.

<pre>Turn 1 starts
[   4|C "Svetlana" H:6] picks [   6|U "Neonyte" A:1 H:5 D:1]
[   4|C "Svetlana" H:6] Protect 1 [   9|U "Neonyte" A:1 H:5 D:1]
[   4|C "Svetlana" H:6] Rally Raider 1 failed because there is no target
Turn 1 ends
Turn 2 starts
[   1|C "Dracorex" H:9] picks [   2|U "Sundering Ogre" A:5 H:5 D:4]
[   1|C "Dracorex" H:9] Weaken 1 failed because there is no target
[  11|U "Sundering Ogre" A:5 H:5 D:4] refreshes 0
Turn 2 ends</pre>

Dracorex should have weakened the Neonyte in Turn 2 as it has only delay 2.
I suspect our change of the timer introduced this.

**Comment by FKuerten** [comment]
Allright. This is bug now. Minimal test case:
QVH0 versus SAAl
surge is irrelevant here. Because of weaken, the Hunter should not be able to do enough damage to kill the Sundering Ogre. We expect Dracorex to win all games.

**Comment by MrHen** [comment]
I think I know where the bug is. Give me a few minutes and I will check.

**Comment by FKuerten** [comment]
already fixed it I think.

Any idea how to turn this issue into a pull request?
I pushed a branch called issue-8

**Comment by MrHen** [comment]
I just opened a pull request and then reference the issue. No idea if there is a better way. I had the Chaos fix in the raid tests branch; just forgot about Weaken and Jam, I guess.

**Comment by FKuerten** [comment]
I just merged it the old fashioned way, should be resolved.
